# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberName', models.CharField(max_length=50)),
                ('memberSurname', models.CharField(max_length=50)),
                ('memberEmailAddress', models.CharField(max_length=50)),
                ('memberTelephoneNumber', models.CharField(max_length=15)),
                ('memberInscriptionDate', models.DateTimeField(verbose_name='Date Inscription')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentType', models.CharField(max_length=50)),
                ('paymentConfirmed', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShareType', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodCoop.Payment'),
        ),
        migrations.AddField(
            model_name='member',
            name='share',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodCoop.Share'),
        ),
    ]
