# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodCoop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='ShareType',
            new_name='shareType',
        ),
    ]
